### ISSUE TITLE
Start week on monday

### ISSUE THREAD

**Issue by Twisterking** [jekor/drcal#2]
Hi there!
I love your minimalistic approach on all your MinJS stuff! :+1: 
But what I think is really missing here is an option to make the week start at mondays! 90% of the world handles it like that haha. Any chance you can implement this little feature?
brest, P

**Comment by jekor** [comment]
Thanks for the suggestion. Let me know if this works for you.

https://github.com/jekor/drcal/commit/6f25cb8f44df863aec6961c891e6d5f339aff5b4
